minwater_review/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^reviews/', include('reviews.urls', namespace="reviews")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace="auth")),

]

reviews/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.review_list, name='review_list'),
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    url(r'^mineralwater$', views.mineralwater_list, name='mineralwater_list'),
    url(r'^mineralwater/(?P<mineralwater_id>[0-9]+)/$', views.mineralwater_detail, name='mineralwater_detail'),
    url(r'^mineralwater/(?P<mineralwater_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^review/user/(?P<username>\w+)/$', views.user_review_list, name='user_review_list'),
    url(r'^review/user/$', views.user_review_list, name='user_review_list'),
    url(r'^recommendation/$', views.user_recommendation_list, name='user_recommendation_list'),
]

reviews/models.py
from django.db import models
from django.contrib.auth.models import User
import numpy as np


class Mineral_Water(models.Model):
    name = models.CharField(max_length=200)

    def average_rating(self):
        all_ratings = map(lambda x: x.rating, self.review_set.all())
        return np.mean(all_ratings)

    def __str__(self):
        return self.name

#imdb style
class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),
    )


    mineralwater = models.ForeignKey(Mineral_Water)
    pub_date = models.DateTimeField('date published')
    user_name = models.CharField(max_length=100)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=RATING_CHOICES)


class Cluster(models.Model):
    name = models.CharField(max_length=100)
    users = models.ManyToManyField(User)

    def get_members(self):
        return "\n".join([u.username for u in self.users.all()])

reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import Review


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),
        }

reviews/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from .models import Review, Mineral_Water, Cluster
from .forms import ReviewForm
from .suggestions import update_clusters

import datetime

from django.contrib.auth.decorators import login_required


def review_list(request):
    latest_review_list = Review.objects.order_by('-pub_date')[:9]
    context = {'latest_review_list': latest_review_list}
    return render(request, 'reviews/review_list.html', context)


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'reviews/review_detail.html', {'review': review})


def mineralwater_list(request):
    mineralwater_list = Mineral_Water.objects.order_by('-name')
    context = {'mineralwater_list': mineralwater_list}
    return render(request, 'reviews/mineralwater_list.html', context)


def mineralwater_detail(request, mineralwater_id):
    mineralwater = get_object_or_404(Mineral_Water, pk=mineralwater_id)
    form = ReviewForm()
    return render(request, 'reviews/mineralwater_detail.html', {'mineralwater': mineralwater, 'form': form})


@login_required
def add_review(request, mineralwater_id):
    mineralwater = get_object_or_404(Mineral_Water, pk=mineralwater_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data['rating']
        comment = form.cleaned_data['comment']
        user_name = request.user.username
        review = Review()
        review.mineralwater = mineralwater
        review.user_name = user_name
        review.rating = rating
        review.comment = comment
        review.pub_date = datetime.datetime.now()
        review.save()
        update_clusters()
        return HttpResponseRedirect(reverse('reviews:mineralwater_detail', args=(mineralwater.id,)))

    return render(request, 'reviews/mineralwater_detail.html', {'mineralwater': mineralwater, 'form': form})


def user_review_list(request, username=None):
    if not username:
        username = request.user.username
    latest_review_list = Review.objects.filter(user_name=username).order_by('-pub_date')
    context = {'latest_review_list': latest_review_list, 'username': username}
    return render(request, 'reviews/user_review_list.html', context)


@login_required
def user_recommendation_list(request):
    user_reviews = Review.objects.filter(user_name=request.user.username).prefetch_related('mineralwater')
    user_reviews_mineralwater_ids = set(map(lambda x: x.mineralwater.id, user_reviews))


    try:
        user_cluster_name = User.objects.get(username=request.user.username).cluster_set.first().name
    except:
        update_clusters()
        user_cluster_name = User.objects.get(username=request.user.username).cluster_set.first().name

    user_cluster_other_members = Cluster.objects.get(name=user_cluster_name).users.exclude(
        username=request.user.username).all()
    other_members_usernames = set(map(lambda x: x.username, user_cluster_other_members))

    other_users_reviews = Review.objects.filter(user_name__in=other_members_usernames).exclude(
        mineralwater__id__in=user_reviews_mineralwater_ids)
    other_users_reviews_mineralwater_ids = set(map(lambda x: x.mineralwater.id, other_users_reviews))

    mineralwater_list = sorted(
        list(Mineral_Water.objects.filter(id__in=other_users_reviews_mineralwater_ids)),
        key=lambda x: x.average_rating,
        reverse=True
    )

    return render(
        request,
        'reviews/userrecommendation_list.html',
        {'username': request.user.username, 'mineralwater_list': mineralwater_list}
    )

reviews/templates/reviews/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">
    <nav  class="navbar navbar-default">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'reviews:review_list' %}">Mineral Water</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'reviews:mineralwater_list' %}">Mineral Water list</a></li>
                <li><a href="{% url 'reviews:review_list' %}">Home</a></li>
            </ul>
        </div>
    </nav>
    

    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}

reviews/templates/reviews/mineralwater_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
<h2>{{ mineralwater.name }}</h2>
<h5>{{ mineralwater.review_set.count }} reviews ({{ mineralwater.average_rating | floatformat }} average rating)</h5>
{% endblock %}

{% block content %}
<h3>Recent reviews</h3>

{% if mineralwater.review_set.all %}
<div class="row">
    {% for review in mineralwater.review_set.all %}
    <div class="col-xs-6 col-lg-4">
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by <a href="{% url 'reviews:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this Mineral Water yet</p>
{% endif %}

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'reviews:add_review' mineralwater.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Add
    </button>
    {% endbuttons %}
</form>
{% endblock %}

reviews/templates/reviews/mineralwater_list.html
{% extends 'base.html' %}

{% block title %}
<h2>Mineral Water list</h2>
{% endblock %}

{% block content %}
{% if mineralwater_list %}
<div class="row">
    {% for mineralwater in mineralwater_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'reviews:mineralwater_detail' mineralwater.id %}">
        {{ mineralwater.name }}
        </a></h4>
        <h5>{{ mineralwater.review_set.count }} reviews</h5>
        <h5>{{ mineralwater.average_rating | floatformat }} average rating</h5>
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No Mineral Water are available.</p>
{% endif %}
{% endblock %}

reviews/templates/reviews/review_detail.html
{% extends 'base.html' %}

{% block title %}
<h2><a href="{% url 'reviews:mineralwater_detail' review.mineralwater.id %}">{{ review.mineralwater.name }}</a></h2>
{% endblock %}

{% block content %}
<h4>Rated {{ review.rating }} of 5 by <a href="{% url 'reviews:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h4>
<p>{{ review.pub_date }}</p>
<p>{{ review.comment }}</p>
{% endblock %}

reviews/templates/reviews/review_list.html
{% extends 'base.html' %}

{% block title %}
<h2>Latest reviews</h2>
{% endblock %}

{% block content %}
{% if latest_review_list %}
<div class="row">
    {% for review in latest_review_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'reviews:review_detail' review.id %}">
        {{ review.mineralwater.name }}
        </a></h4>
        <h6>Rated {{ review.rating }} of 5 by <a href="{% url 'reviews:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h6>
        <p>{{ review.comment }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}

reviews/templates/reviews/user_review_list.html
{% extends 'reviews/review_list.html' %}

{% block title %}
<h2>Reviews by {{ username }}</h2>
{% endblock %}

reviews/templates/reviews/userrecommendation_list.html
{% extends 'reviews/mineralwater_list.html' %}

{% block title %}
<h2>Mineral Water suggestions for {{ username }}</h2>
{% endblock %}

templates/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">
    <nav class="navbar navbar-inverse">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'reviews:review_list' %}">MineralWater</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'reviews:mineralwater_list' %}">Mineral Water list</a></li>
                <li><a href="{% url 'reviews:review_list' %}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'reviews:user_review_list' user.username %}">Hello {{ user.username }}</a></li>
                <li><a href="{% url 'reviews:user_recommendation_list' %}">Mineral Water suggestions</a></li>
                <li><a href="{% url 'auth:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'auth:login' %}">Login</a></li>
                <li><a href="/accounts/register">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    

    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}